---
- name: Update apt cache.
  apt: update_cache=yes

- name: Install packages.
  apt: "name={{ item }} state=installed install_recommends=no"
  with_items: packages

- name: Remove locks.
  command: rm -rf /var/lib/apt/lists/*
